// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Classphy.Server.Entities;

public partial class Asignaturas
{
    public int idAsignatura { get; set; }

    public string Nombre { get; set; }

    public int idPeriodo { get; set; }

    public string Descripcion { get; set; }
}