// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Classphy.Server.Entities;

public partial class Asistencias
{
    public int idAsistencia { get; set; }

    public int idAsignatura { get; set; }

    public int idEstudiante { get; set; }

    public DateTime Fecha { get; set; }

    public bool Presente { get; set; }
}