// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Classphy.Server.Entities;

public partial class Estudiantes
{
    public int idEstudiante { get; set; }

    public int idUsuario { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public string Matricula { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public string Genero { get; set; }
}