// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Classphy.Server.Entities;

public partial class Usuarios
{
    public int idUsuario { get; set; }

    public int idPerfil { get; set; }

    public string NombreUsuario { get; set; }

    public string Contraseña { get; set; }

    public string Nombres { get; set; }

    public string Apellidos { get; set; }

    public DateTime FechaRegistro { get; set; }

    public bool Activo { get; set; }

    public string CorreoElectronico { get; set; }
}